# Generated by Django 5.2.1 on 2026-03-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_image',
            field=models.URLField(blank=True),
        ),
    ]
