# Generated by Django 5.2.1 on 2026-03-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_featuredproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='1AFD', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_unit',
            field=models.CharField(blank=True, choices=[('st', 'st'), ('bu', 'bu')], default='', max_length=4),
        ),
    ]
