# Generated by Django 5.2.1 on 2026-03-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_checkout_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='pack_quantity',
            field=models.CharField(choices=[(175, '175'), (200, '200'), (250, '250'), (120, '120'), (30, '30'), (32, '32'), (15, '15'), (16, '16'), (18, '18'), (80, '80'), (12, '12'), (10, '10'), (13, '13'), (10, '10'), (40, '40'), (70, '70'), (34, '34'), (50, '50'), (9, '9'), (90, '90'), (14, '14')], default=50, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Roses', 'Roses'), ('Spray Roses', 'Spray Roses'), ('6 Roses Bqt', '6 Roses Bouquets'), ('1 St Rose Bqt', 'Rose Bouquets'), ('Bouquets 12 Stem', 'Bouquets 12 Stem'), ('Carnations', 'Carnations'), ('Mini Carnations', 'Mini Carnations'), ('Dianthus', 'Dianthus'), ('Statice', 'Statice'), ('Snapdragons', 'Snapdragons'), ('Asters', 'Asters'), ('Gypsophilia', 'Gypsophilia'), ('Lilies Oriental', 'Lilies Oriental'), ('Lilies L.A. Hybrid', 'Lilies L.A. Hybrid'), ('Hydrangeas', 'Hydrangeas'), ('Alstromeria', 'Alstromeria'), ('Hypericum', 'Hypericum'), ('Pom Poms', 'Pom Poms'), ('Mums Fuji or Cremon', 'Mums Fuji or Cremon'), ('Supermums', 'Supermums'), ('Limonium', 'Limonium'), ('Sinensis', 'Sinensis')], default='Roses', max_length=50),
        ),
    ]
