# Generated by Django 5.2.1 on 2026-03-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pack_quantity',
            field=models.CharField(choices=[(175, '175'), (200, '200'), (250, '250'), (120, '120'), (30, '30'), (32, '32'), (15, '15'), (16, '16'), (18, '18'), (80, '80'), (12, '12'), (10, '10'), (13, '13'), (10, '10'), (40, '40'), (70, '70'), (34, '34'), (50, '50'), (9, '9'), (90, '90'), (14, '14')], max_length=50),
        ),
    ]
